<?php

use App\Enums\AdvertisementPlaceEnum;
use App\Enums\AdvertisementUrlTargetEnum;
use App\Enums\ImageSizeTypeEnum;
use App\Enums\NewsTypeEnum;
use App\Enums\VideoTypeEnum;
use App\Enums\MaterialTypeEnum;
use App\Enums\ParticipantTypeEnum;
use App\Enums\LinkStatusEnum;
use App\Enums\CategoryStyleEnum;
use App\Enums\CategoryTypeEnum;
use App\Enums\TagTypeEnum;
use App\Enums\DateTypeEnum;

$default = [
    // Frontend languages available for this project
    // key = locale code, value = enabled (true/false)
    // Only languages that are also enabled in config/app.php will work
    'frontend_languages' => [
        'ar' => true,
        'en' => false,
        'tr' => false,
    ],

    // Default frontend language for this project
    'default_frontend_language' => 'ar',

    'permissions' => array_fill_keys([
        'posts', 'sort_contents', 'breaking_news', 'categories', 'types', 'icons',
        'special_files', 'tags', 'quotes', 'special_pages', 'advertisements', 'events',
        'users', 'permissions', 'user_logs', 'settings', 'publish_roles', 'pending_actions',
        'navbar_links', 'contact_us', 'send_news', 'roles', 'alerts', 'user_details',
        'news_letter_emails', 'participants', 'materials', 'materials_albums', 'data_page',
        'social_media', 'reels', 'courses', 'import', 'services', 'applications',
        'subscribers', 'subscriptions', 'subscriber_notifications', 'settings_landing_page_information',
    ], true),

    'category_type' => array_fill_keys(
        array_column(CategoryTypeEnum::cases(), 'name'),
        false
    ),

    'advertisement_place' => array_fill_keys(
        array_column(AdvertisementPlaceEnum::cases(), 'name'),
        true
    ),

    'advertisement_url_target' => array_fill_keys(
        array_column(AdvertisementUrlTargetEnum::cases(), 'name'),
        true
    ),

    'image_size_type' => array_fill_keys(
        array_column(ImageSizeTypeEnum::cases(), 'name'),
        false
    ),

    'category_style_enum' => array_fill_keys(
        array_column(CategoryStyleEnum::cases(), 'name'),
        false
    ),

    'link_status' => array_fill_keys(
        array_column(LinkStatusEnum::cases(), 'name'),
        true
    ),

    'material_type' => array_fill_keys(
        array_column(MaterialTypeEnum::cases(), 'name'),
        true
    ),

    'participant_type' => array_fill_keys(
        array_column(ParticipantTypeEnum::cases(), 'name'),
        true
    ),

    'tag_type' => array_fill_keys(
        array_column(TagTypeEnum::cases(), 'name'),
        false
    ),

    'video_type' => array_fill_keys(
        array_column(VideoTypeEnum::cases(), 'name'),
        true
    ),

    'date_type' => array_fill_keys(
        array_column(DateTypeEnum::cases(), 'name'),
        true
    ),
];


// تخصيصات حسب نوع المشروع
$customizations = [
    'palestine_post' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
            'scholarships' => true
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'events' => false,
            'breaking_news' => false,
            'advertisements' => false,
            'user_details' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,

        ],
        'image_size_type' => [
            'LARGE_IMAGE' => true,
            'MID_IMAGE' => true,
            'SMALL_IMAGE' => true,
            'COVER_ARTICLE' => true,
            'SIDE_POST' => true,
        ],
        'category_type' => [
            'NEWS' => true,
            'PODCAST' => true,
            'VIDEO' => true,
        ],
        'material_type' => [
            'IMAGE' => false,
        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'جميع الأخبار' => '/all_posts',
                'ألبومات الفيديو' => '/all_videos',
                'ألبومات البودكاست' => '/all_podcasts',
                'أرسل خبر' => '/send_news',
            ],
        ],
        'routes_map' => [
            'CATEGORY' => '/category_news/{category_title}',
            'TAG' => '/tag_news/{tag_title}',
            'PODCAST' => '/single_podcast/{podcast_album_id}/{album_name}',
            'VIDEO' => '/single_video/{id}/{category_title}',
            'SPECIAL_PAGE' => '/special_page/{id}/{page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'required|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],
    'alarouri' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
            'scholarships' => false
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'events' => false,
            'breaking_news' => false,
            'advertisements' => false,
            'user_details' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,

        ],
//        'image_size_type' => [
//            'LARGE_IMAGE' => true,
//            'MID_IMAGE' => true,
//            'SMALL_IMAGE' => true,
//            'COVER_ARTICLE' => true,
//            'SIDE_POST' => true,
//        ],
        'category_type' => [
            'NEWS' => true,
            'PODCAST' => true,
            'VIDEO' => true,
            'IMAGE' => true,
        ],
//        'material_type' => [
//            'IMAGE' => false,
//        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
            ],
        ],
        'routes_map' => [
            'SPECIAL_PAGE' => '/special_page/{id}/{page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'nullable|string|max:500',
            ]
        ],
    ],
    'adani_cast' => [
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => true,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'article_image' => '220x160',
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'posts' => false,
            'sort_contents' => false,
            'quotes' => false,
            'events' => false,
            'special_files' => false,
            'publish_roles' => false,
            'roles' => false,
            'send_news' => false,
            'news_letter_emails' => false,
            'types' => false,
            'breaking_news' => false,
            'advertisements' => false,
            'user_details' => false,
            'data_page' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
        ],
        'category_type' => [
            'PODCAST' => true,
        ],
        'material_type' => [
            'IMAGE' => false,
            'VIDEO' => false,
        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'AUTHORS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'category_style_enum' => [
            'ONE_BIG_FOUR_SMALL_STYLE' => true,
            'FOUR_BIG_REST_SMALL_STYLE' => true,
            'ONE_BIG_TWO_MID_STYLE' => true,
            'THREE_MID_WITH_SUB_STYLE' => true,
            'THREE_PODCAST_STYLE' => true,
            'ONE_BIG_THREE_MID_VIDEO_STYLE' => true,
            'TWO_BIG_FOUR_MID_STYLE' => true,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'التواصل معنا' => '/contact_us',
            ],
            'SPECIAL_PAGE' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/category_news/{id}/{category_title}',
            'TAG' => '/tag_news/{id}/{tag_title}',
            'PODCAST' => '/all_podcast/{id}/{podcast_title}',
            'VIDEO' => '/single_video/{id}/{video_title}',
            'SPECIAL_PAGE' => '/special_page/{id}/{special_page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ]
    ],//done
    'cillium_fm' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => true,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'sort_contents' => false,
            'breaking_news' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
            'materials' => false,
            'materials_albums' => false,
            'send_news' => false,
            'news_letter_emails' => false,
        ],
        'advertisement_place' => [
            'MAIN_ADS' => false,
        ],
        'category_type' => [
            'NEWS' => true,
            'EVENTS' => true,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'EVENTS' => true,
        ],
        'date_type' => [
            'date_time' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'تواصل معنا' => '/contact_us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'TAG' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/category-posts/{id}',
            'SPECIAL_PAGE' => '/special_page/{id}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],//done
    'ufok' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'category_type' => [
            'PODCAST' => true,
            'VIDEO' => true,
        ],
        'category_style_enum' => [
            'ONE_BIG_FOUR_SMALL_STYLE' => true,
            'FOUR_BIG_REST_SMALL_STYLE' => true,
            'ONE_BIG_TWO_MID_STYLE' => true,
            'THREE_MID_WITH_SUB_STYLE' => true,
            'THREE_PODCAST_STYLE' => true,
            'ONE_BIG_THREE_MID_VIDEO_STYLE' => true,
            'TWO_BIG_FOUR_MID_STYLE' => true,
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],//done
    'tamkeen' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>false,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'category_type' => [
            'NEWS' => true,
            'PODCAST' => true,
            'VIDEO' => true,
            'EVENTS' => true,
        ],
        'material_type' => [
            'IMAGE' => false,
        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'EVENTS' => true,
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'أرسل خبر' => '/send_news',
            ],
        ],
        'routes_map' => [
            'CATEGORY' => '/category_news/{id}/{category_title}',
            'TAG' => '/tag_news/{id}/{tag_title}',
            'PODCAST' => '/all_podcast/{id}/{podcast_title}',
            'VIDEO' => '/single_video/{id}/{video_title}',
            'SPECIAL_PAGE' => '/special_page/{id}/{page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'required|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],//done
    'almohajer' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => true,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => true,
            'has_whatsapp_link' => true,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => true,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'settings_landing_page_information' => false,
            'advertisements' => false,
            'send_news' => false,
            'sort_contents' => false,
            'breaking_news' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'events' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
            'materials' => false,
            'materials_albums' => false,

        ],
        'category_type' => [
            'NEWS' => true,
        ],
        'tag_type' => [
            'NEWS' => true,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PRESENTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'category_style_enum' => [
            'FOUR_MID_ONE_MID_SLIDER_TWO_SUB' => true,
            'EIGHT_MID_EIGHT_SMALL_SUB' => true,
            'ONE_MID_SLIDER_THREE_SUB' => true,
            'ONE_MID_THREE_SUB' => true,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'بيانات' => '/info',
                'من نحن' => '/about_us',
                'تواصل معنا' => '/contact_us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'TAG' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/all_posts/category/{id}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],//done
    'almashhad' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'main_menu' => true,
            'sub_navbar' =>true,
            'footer_links' => true,
            'social_media' => true,
            'categories' =>true,
            'types' => false,
        ],
        'permissions' => [
            'sort_contents' => false,
            'reels' => false,
            'quotes' => false,
            'events' => false,
            'special_files' => false,
            'publish_roles' => false,
            'roles' => false,
            'send_news' => false,
            'types' => false,
            'breaking_news' => false,
            'advertisements' => false,
            'user_details' => false,
            'data_page' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'category_type' => [
            'PODCAST' => true,
            'VIDEO' => true,
            'NEWS' => true
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => true,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'category_style_enum' => [
            'ONE_BIG_FOUR_SMALL_STYLE' => true,
            'FOUR_BIG_REST_SMALL_STYLE' => true,
            'ONE_BIG_TWO_MID_STYLE' => true,
            'THREE_MID_WITH_SUB_STYLE' => true,
            'THREE_PODCAST_STYLE' => true,
            'ONE_BIG_THREE_MID_VIDEO_STYLE' => true,
            'TWO_BIG_FOUR_MID_STYLE' => true,
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about-us',
                'تواصل معنا' => '/contact-us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'SPECIAL_PAGE' => false,
            'TAG' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/search/{id}',
            'CUSTOM_LINK' => '',
        ],
    ],//done
    'hodhod' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => true,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
                'large_image' => '400x265',
                'avatar_author' => '80x80',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
                'banner' => '600x400',
            ],
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',//tayqan
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
            'advertisements' => [
                'main_image' => '600x400',
            ],

        ],
        'permissions' => [
            'sort_contents' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'advertisements' => false,
            'events' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
            'materials' => false,
            'materials_albums' => false,
        ],
        'category_type' => [
            'NEWS' => true,
            'VIDEO' => false,
        ],
        'category_style_enum' => [
            'ONE_BIG_THREE_MID_STYLE' => true,
            'ONE_BIG_FOUR_MID_VIDEO_STYLE' => true,
            'ONE_MID_WITH_THREE_SUB_STYLE' => true,
            'THREE_MID_WITH_SLIDER_STYLE' => true,
            'TWO_BIG_THREE_MID_STYLE' => true,
            'ONE_BIG_FOUR_MID_STYLE' => true,
            'ONE_BIG_ONE_WIDE_TWO_MID_STYLE' => true,
        ],
        'material_type' => [
            'IMAGE' => false,
            'PODCAST' => false,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => false,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'تواصل معنا' => '/contact_us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'SPECIAL_PAGE' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/all_posts?category_id={id}',
            'TAG' => '/all_posts?tag_id={id}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],//done
    'hongora' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'category_type' => [
            'PODCAST' => true,
            'VIDEO' => true,
        ],
        'category_style_enum' => [
            'ONE_BIG_FOUR_SMALL_STYLE' => true,
            'FOUR_BIG_REST_SMALL_STYLE' => true,
            'ONE_BIG_TWO_MID_STYLE' => true,
            'THREE_MID_WITH_SUB_STYLE' => true,
            'THREE_PODCAST_STYLE' => true,
            'ONE_BIG_THREE_MID_VIDEO_STYLE' => true,
            'TWO_BIG_FOUR_MID_STYLE' => true,
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'عن حنجرة' => '/about_us',
                'حنجرة بودكاست' => '/all_podcast_albums',
                'فريق حنجرة' => '/teams',
                'خدمات حنجرة' => '/services',
                'احجز الاستوديو' => '/studio',
                'تواصل معنا' => '/contact_us',
            ],
            'PODCAST' => true,
            'VIDEO' => false,
            'TAG' => false,
        ],
    ],
    'alahed' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => true,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'special_content_available' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],

        'category_type' => [
            'PODCAST' => true,
            'VIDEO' => true,
        ],
        'category_style_enum' => [
            'ONE_BIG_FOUR_SMALL_STYLE' => true,
            'FOUR_BIG_REST_SMALL_STYLE' => true,
            'ONE_BIG_TWO_MID_STYLE' => true,
            'THREE_MID_WITH_SUB_STYLE' => true,
            'THREE_PODCAST_STYLE' => true,
            'ONE_BIG_THREE_MID_VIDEO_STYLE' => true,
            'TWO_BIG_FOUR_MID_STYLE' => true,
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],
    'maktoob' => [

        'frontend_languages' => [
            'en' => true,
            'ar' => false,
            'tr' => false,
        ],
        'default_frontend_language' => 'en',

        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => true,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => true,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'sort_contents' => false,
            'send_news' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'events' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
        ],
        'category_type' => [
            'NEWS' => true,
            'VIDEO' => true,
        ],
        'material_type' => [
            'PODCAST' => false,
            'IMAGE' => false,
        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PRESENTERS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'GUESTS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'advertisement_place' => [
            'SIDE_ADS' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'Home' => '/',
                'About Us' => '/about_us',
                'Contact Us' => '/contact_us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'TAG' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/all_posts/{id}',
            'SPECIAL_PAGE' => '/special_page/{id}',
            'CUSTOM_LINK' => '',
        ],
        'category_style_enum' => [
            'ONE_MID_WITH_VERTICAL_SLIDER' => true,
            'FOUR_MID_WITH_SUB_STYLE' => true,
            'ONE_BIG_WITH_FOUR_SUB_STYLE' => true,
            'ONE_BIG_VIDEO_WITH_THREE_SUB' => true,
            'THREE_MID_SLIDER_STYLE' => true,
            'THREE_MID_SLIDER_DARK_STYLE' => true,
            'TWO_CATEGORY_STYLE' => true
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'nullable|string|max:500',
                'tags'=>'required|string',
            ]
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
    ],
    'almaidan' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'sort_contents' => false,
            'breaking_news' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'special_pages' => false,
            'advertisements' => false,
            'events' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
            'materials' => false,
            'materials_albums' => false,
        ],
        'category_type' => [
            'NEWS' => true,
        ],
        'category_style_enum' => [
            'SIX_WIDTH_MID_STYLE' => true,
            'FOUR_MID_STYLE' => true,
            'THREE_HEIGHT_MID_STYLE' => true,
        ],
        'material_type' => [
            'PODCAST' => false,
            'IMAGE' => false,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PRESENTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about_us',
                'تواصل معنا' => '/contact_us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'SPECIAL_PAGE' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/all_posts/category/{id}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],
    'quds' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>true,
            'types' => false,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => false,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'sort_contents' => false,
            'breaking_news' => false,
            'types' => false,
            'special_files' => false,
            'quotes' => false,
            'advertisements' => false,
            'events' => false,
            'publish_roles' => false,
            'roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,


        ],
        'category_type' => [
            'NEWS' => true,
            'VIDEO' => true,
        ],
        'category_style_enum' => [
            'ONE_HEIGHT_SIX_SUB' => true,
            'SIX_SLIDER' => true,
            'ONE_HEIGHT_FOUR_SUB' => true,
            'THREE_MID_WITH_THREE_SUB_SMALL' => true,
        ],
        'material_type' => [
            'IMAGE' => false,
            'PODCAST' => false,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
            'MATERIALS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'Home' => '/',
                'About Us' => '/about_us',
                'Contact Us' => '/contact_us',
//                'All Posts' => '/all_posts',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'TAG' => false,
            'TYPE' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/all_posts/category/{id}',
//            'TAG' => '/all_posts/tag/{id}',
            'SPECIAL_PAGE' => '/special_page/{id}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'nullable|string',
            ]
        ],
    ],//done
    'tayqan' => [
        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => true,
            'resource' => true,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => false,
            'available_at' => false,
            'type' => true,
        ],
        'nav_links_access' =>[
            'social_media' => true,
            'footer_links' => true,
            'main_menu' => true,
            'sub_navbar' =>true,
            'categories' =>false,
            'types' => true,
        ],
        'general' => [
            'scholarships' => false,
            'has_claim' => true,
            'has_landing_page' => false,
            'has_publishers' => true,
            'has_resources' => true,
            'has_post_available_date' => false,
            'has_whatsapp_link' => true,
            'has_claim_url' => true,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '600x400',
                'social_media_image' => '600x400',
                'slider_image' => '600x400',
                'portrait_image' => '600x400',
            ],
            'material' => [
                'main_image' => '600x400',
            ],
            'material_album' => [
                'main_image' => '600x400',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '600x400',
            ],
            'advertisements' => [
                'main_image' => '600x400',
            ],
            'subscriber_image' => '600x400',
            'recent_post' => '100x100',
            'event_image' => '600x400',
            'category_image' => '600x400',
            'service_image' => '600x400',
            'article_image' => '800x400',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'presenter_image' => '500x600',
            'gallery_items' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '600x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'landing_page' => [
                'top_left' => '400x400',
                'top_right' => '400x400',
                'bottom_left' => '400x400',
                'bottom_right' => '400x400',
            ],
            'studio' =>[
                'tools_box' => '250x160',
            ],
            'podcast_album' => '400x400',
            'podcast_track' => '600x400',
            'podcast_image' => '800x400',
            'scholarship_image' => '1600x900',
            'podcast_small_image' =>'400x400',
            'podcast_background_image' =>'400x400',
            'video_size' => '400x265',
            'video_container' => '200x140',
            'video_image' => '600x400',
            'main_video' => '800x400',
            'data_page' => [
                'author_image' => '600x400',
            ],
            'avtar-author' => '50x50',
        ],
        'permissions' => [
            'events' => false,
            'breaking_news' => false,
            'advertisements' => false,
            'sort_contents' => false,
            'quotes' => false,
            'special_files' => false,
            'materials' => false,
            'materials_albums' => false,
            'publish_roles' => false,
            'user_details' => false,
            'data_page' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
        ],
        'category_type' => [
            'NEWS' => true,
        ],
        'participant_type' => [
            'GUESTS' => false,
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PRESENTERS' => false,
            'PUBLISHERS' => false,
            'RESOURCES' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'من نحن' => '/about-us',
            ],
            'PODCAST' => false,
            'VIDEO' => false,
            'TAG' => false,
        ],
        'routes_map' => [
            'CATEGORY' => '/Categoryclaim/{category_title}',
            'TYPE' => '/ClaimType/{type_name}',
            'SPECIAL_PAGE' => '/special_page/{id}/{page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'nullable|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags'=>'required|string',
            ]
        ],
    ],

    // =============================================
    // FiMED - المؤسسة الفلسطينية للإعلام
    // =============================================
    'fimed' => [
        'frontend_languages' => [
            'ar' => true,
            'tr' => true,
            'en' => false,
        ],
        'default_frontend_language' => 'ar',

        'post_columns' => [
            'order' => false,
            'post_id' => true,
            'title' => true,
            'category' => true,
            'views' => true,
            'admin' => true,
            'author' => true,
            'publisher' => false,
            'resource' => false,
            'publish_time' => true,
            'updates' => true,
            'actions' => true,
            'tags' => true,
            'available_at' => false,
            'type' => false,
        ],
        'nav_links_access' => [
            'main_menu' => true,
            'sub_navbar' => false,
            'footer_links' => true,
            'social_media' => true,
            'categories' => true,
            'types' => false,
        ],
        'general' => [
            'has_claim' => false,
            'has_landing_page' => false,
            'has_publishers' => false,
            'has_resources' => true,
            'has_post_available_date' => false,
            'has_whatsapp_link' => false,
            'has_claim_url' => false,
            'has_podcast_url' => false,
            'has_banner' => false,
            'special_content_available' => false,
            'scholarships' => false,
        ],
        'image_sizes' => [
            'post' => [
                'main_image' => '900x600',
                'social_media_image' => '600x400',
                'slider_image' => '1200x600',
                'portrait_image' => '600x800',
            ],
            'settings' => [
                'footer_logo' => '600x400',
                'site_logo' => '600x400',
                'favicon_image' => '64x64',
            ],
            'advertisements' => [
                'main_image' => '970x250',
            ],
            'recent_post' => '100x100',
            'category_image' => '600x400',
            'article_image' => '900x600',
            'card_image' => '400x265',
            'file_image' => '600x400',
            'blog_thumb' => '900x600',
            'post_preview' => '900x600',
            'about_us' => '800x500',
            'participant_image' => '400x400',
            'image_editor' => [
                'water_mark' => '400x400',
            ],
            'avtar-author' => '80x80',
        ],
        'permissions' => [
            'events' => false,
            'breaking_news' => false,
            'reels' => false,
            'courses' => false,
            'import' => false,
            'services' => false,
            'applications' => false,
            'subscribers' => false,
            'subscriptions' => false,
            'subscriber_notifications' => false,
            'materials' => false,
            'materials_albums' => false,
            'data_page' => false,
            'user_details' => false,
        ],
        'image_size_type' => [
            'LARGE_IMAGE' => true,
            'MID_IMAGE' => true,
            'SMALL_IMAGE' => true,
            'COVER_ARTICLE' => true,
            'SIDE_POST' => true,
        ],
        'category_type' => [
            'NEWS' => true,
        ],
        'category_style_enum' => [
            'FIMED_REPORTS' => true,
            'FIMED_DARK_VOICE' => true,
            'FIMED_CATEGORY_GRID' => true,
            'FIMED_OPINION' => true,
        ],
        'material_type' => [
            'PODCAST' => false,
            'VIDEO' => false,
            'IMAGE' => false,
        ],
        'participant_type' => [
            'CLIENTS' => false,
            'PARTNERS' => false,
            'TEAM' => false,
            'SUPPORTERS' => false,
            'PRESENTERS' => false,
            'GUESTS' => false,
        ],
        'tag_type' => [
            'NEWS' => true,
        ],
        'video_type' => [
            'TELEGRAM' => false,
        ],
        'link_status' => [
            'default_pages' => [
                'الرئيسية' => '/',
                'جميع المقالات' => '/all_posts',
                'من نحن' => '/about_us',
                'تواصل معنا' => '/contact_us',
                'أرسل خبر' => '/send_news',
            ],
        ],
        'routes_map' => [
            'CATEGORY' => '/category_news/{category_title}',
            'TAG' => '/tag_news/{tag_title}',
            'SPECIAL_PAGE' => '/special_page/{id}/{page_title}',
            'CUSTOM_LINK' => '',
        ],
        'input_validation' => [
            'post' => [
                'image_size' => 'required|integer|in:' . join(",", array_column(ImageSizeTypeEnum::cases(), 'value')),
                'news_type' => 'nullable|integer|in:' . join(",", array_column(NewsTypeEnum::cases(), 'value')),
                'description' => 'required|string|max:500',
                'tags' => 'required|string',
            ],
        ],
    ],
];

$launch = config('app.launch');

return isset($customizations[$launch])
    ? array_replace_recursive($default, $customizations[$launch])
    : $default;
